# Generated by Django 5.0.4 on 2024-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_direccion_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='manzana',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_lote',
            field=models.CharField(max_length=100),
        ),
    ]
